// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3X8X2BlfMD4nw2qkMwgGKrNsxJyQ-7Vs',
    appId: '1:562638772856:web:79c40fbf3af068ec272b8d',
    messagingSenderId: '562638772856',
    projectId: 'chat-app-5b859',
    authDomain: 'chat-app-5b859.firebaseapp.com',
    storageBucket: 'chat-app-5b859.appspot.com',
    measurementId: 'G-31S6512GQK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmSTkJQ6BKtHWOCtvcMB4TfjS1P5AqLEo',
    appId: '1:562638772856:android:4aeb1b02e0b7c23a272b8d',
    messagingSenderId: '562638772856',
    projectId: 'chat-app-5b859',
    storageBucket: 'chat-app-5b859.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtzmgq6ZaUhQSMezCZIWzxI3L488QYlXU',
    appId: '1:562638772856:ios:e89071f9bf760a60272b8d',
    messagingSenderId: '562638772856',
    projectId: 'chat-app-5b859',
    storageBucket: 'chat-app-5b859.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtzmgq6ZaUhQSMezCZIWzxI3L488QYlXU',
    appId: '1:562638772856:ios:e89071f9bf760a60272b8d',
    messagingSenderId: '562638772856',
    projectId: 'chat-app-5b859',
    storageBucket: 'chat-app-5b859.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3X8X2BlfMD4nw2qkMwgGKrNsxJyQ-7Vs',
    appId: '1:562638772856:web:edf0493b922e4bf6272b8d',
    messagingSenderId: '562638772856',
    projectId: 'chat-app-5b859',
    authDomain: 'chat-app-5b859.firebaseapp.com',
    storageBucket: 'chat-app-5b859.appspot.com',
    measurementId: 'G-GJ41SQEH6R',
  );

}